services:
  nextjs:
    platform: linux/amd64
    build: ./
    image: eddiefahrenheit/githubportfolio-nextjs
  nginx:
    platform: linux/amd64
    build: ./nginx/
    image: eddiefahrenheit/githubportfolio-nginx
    ports:
      - 80:80
